version: '2'

services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile-jenkins
    environment:
      JAVA_OPTS: "-Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=1000"
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: registry
    ports:
      - "5000:5000"
    volumes:
      - ./registry:/var/lib/registry
